name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r . ec2-user@ec2-52-205-181-133.compute-1.amazonaws.com:/home/ec2-user/relif-zeller

    - name: Install dependencies and start application
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@ec2-52-205-181-133.compute-1.amazonaws.com << 'EOF'
          cd /home/ec2-user/relif-zeller
          npm install
          pm2 stop all || true
          pm2 start index.js
        EOF
